### ISSUE TITLE
Plugin does't send the actual exception class to airbrake

### ISSUE THREAD

**Issue by johntowell** [coderberry/airbrake-grails#35]
Wonderful plugin.  It sends a lot of good information to airbrake, but I am missing the actual exception that was thrown.  It looks like the title is the exception message, and the Backtrace is the full stacktrace except for the final exception.  Some configuration I am missing?

**Comment by jonspalmer** [comment]
I haven't seen that problem. Grails can be a little squirly about exception traces. Can you provide a reproducible example or better yet a failing test?

**Comment by johntowell** [comment]
Hmm it must be something with our configuration then, because it happens for every exception.  

In our logs we see

```
2013-05-14 12:01:21,401 [ajp-8009-5] ERROR errors.GrailsExceptionResolver  - SSLPeerUnverifiedException occurred when processing request: [PUT] /api_2_0/
peer not authenticated. Stacktrace follows:
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
    at com.sun.net.ssl.internal.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:352)
    at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:126)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:437)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:151)
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:125)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:334)
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:281)
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestGet(RestStorageService.java:981)
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.listAllBucketsImpl(RestStorageService.java:1373)
    at org.jets3t.service.StorageService.listAllBucketsImpl(StorageService.java:1379)
    at org.jets3t.service.StorageService.listAllBuckets(StorageService.java:563)
    at org.jets3t.service.S3Service.listAllBuckets(S3Service.java:1367)
    at org.jets3t.service.S3Service.listAllBuckets(S3Service.java:84)
    at org.jets3t.service.StorageService.getBucket(StorageService.java:729)
    at org.jets3t.service.S3Service.getBucket(S3Service.java:1909)
    at our code removed
```

However in airbrake we are missing the javax.net.ssl.SSLPeerUnverifiedException class.  The title of the airbrake error is `peer not authenticated` and the backtrace tab says

```
SSLSessionImpl.java:352:in `com.sun.net.ssl.internal.ssl.SSLSessionImpl.getPeerCertificates'
AbstractVerifier.java:126:in `org.apache.http.conn.ssl.AbstractVerifier.verify'
SSLSocketFactory.java:437:in `org.apache.http.conn.ssl.SSLSocketFactory.connectSocket'
DefaultClientConnectionOperator.java:180:in `org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection'
AbstractPoolEntry.java:151:in `org.apache.http.impl.conn.AbstractPoolEntry.open'
AbstractPooledConnAdapter.java:125:in `org.apache.http.impl.conn.AbstractPooledConnAdapter.open'
DefaultRequestDirector.java:643:in `org.apache.http.impl.client.DefaultRequestDirector.tryConnect'
DefaultRequestDirector.java:479:in `org.apache.http.impl.client.DefaultRequestDirector.execute'
AbstractHttpClient.java:906:in `org.apache.http.impl.client.AbstractHttpClient.execute'
AbstractHttpClient.java:805:in `org.apache.http.impl.client.AbstractHttpClient.execute'
RestStorageService.java:334:in `org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest'
RestStorageService.java:281:in `org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest'
RestStorageService.java:981:in `org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestGet'
RestStorageService.java:1373:in `org.jets3t.service.impl.rest.httpclient.RestStorageService.listAllBucketsImpl'
StorageService.java:1379:in `org.jets3t.service.StorageService.listAllBucketsImpl'
StorageService.java:563:in `org.jets3t.service.StorageService.listAllBuckets'
S3Service.java:1367:in `org.jets3t.service.S3Service.listAllBuckets'
S3Service.java:84:in `org.jets3t.service.S3Service.listAllBuckets'
StorageService.java:729:in `org.jets3t.service.StorageService.getBucket'
S3Service.java:1909:in `org.jets3t.service.S3Service.getBucket'
```

Do you have any pointers on specific exception resolvers we should be using?

**Comment by khelenek** [comment]
The plugin does not seem to send the "chain of exceptions", so for most exceptions you just get the unhelpful, top level wrapped exception and not the root cause exception. There doesn't appear to be any way to influence how the throwable gets converted into a backtrace.
