### ISSUE TITLE
support for grails 3

### ISSUE THREAD

**Issue by meltzow** [coderberry/airbrake-grails#40]
hi,
any plans here?

**Comment by meltzow** [comment]
any news here?

**Comment by jonspalmer** [comment]
Pull requests happily accepted. At the moment I'm short of time to do it myself but might find a moment sometime in the next few weeks.

**Comment by jonspalmer** [comment]
I have a grails-3.0 branch that has my first attempt at a fix. Should be a version in the grails plugin repo too. Would be good to have someone else verify that it works.

**Comment by MarcAtRiflmedia** [comment]
A working version is in my grails-3.1.4 branch. 
Before the service was working but not the AirbrakeAppender.

**Comment by MarcAtRiflmedia** [comment]
Sorry if i made some mistakes in what i did, It's the first time i use github.

**Comment by meltzow** [comment]
hi, 
i tried your branch. thx. for that. 
But If i try to send a notification by hand in a controller with airbrakeService.notify(null, [errorMessage: 'Something went wrong']) .  I got a 
Cannot invoke method notify() on null object. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Cannot invoke method notify() on null object
        at grails.plugins.airbrake.AirbrakeService.notify(AirbrakeService.groovy:9)
        at fahrer.portal.WelcomeController$_closure1.doCall(WelcomeController.groovy:12)
        ... 3 common frames omitted
looks like airbrakeNotifier in AirbrakeService is null. 
I use grails 3.1.9. 
any idea to solve it?

**Comment by MarcAtRiflmedia** [comment]
Hello,
It's a problem i got with grails-3.0 branch but it seems to work fine for me with grails 3.1.4 and the grails-3.1.4 branch

**Comment by meltzow** [comment]
ok, a investigation finds out the doWithSpring in AirbrakeGrailsPlugin.groovy isnt execute at starttime. But I dont know why.

**Comment by meltzow** [comment]
hi,
just a question: any plans to merge the PR? We migrated to grails3 and this is the last plugin we need. 
thx

**Comment by rvargas** [comment]
Please, merge the PR.

Update: Please :(

**Comment by rvargas** [comment]
Thanks @meltzow your PR help us to get airbrake on our Grails 3 app.
